name: Deploy to clojars

on:
  push:
    branches: [ "master" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Prepare java
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '21'

    - name: Install clojure tools
      uses: DeLaGuardo/setup-clojure@11.0
      with:
        clj-kondo: 2023.07.13
        cli: 1.11.1.1347
        bb: 1.3.184

    - name: Cache clojure dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.m2/repository
          ~/.gitlibs
          ~/.deps.clj
        key: cljdeps-${{ hashFiles('deps.edn') }}
        restore-keys: cljdeps-

    - name: Build
      run: clojure -T:build jar

    - name: Deploy
      run: clojure -X:deploy
      env:
        CLOJARS_PASSWORD=${{ secrets.CLOJARS_PASSWORD }}
        CLOJARS_USERNAME=${{ env.CLOJARS_USERNAME }}
